require:
  - rubocop-rails
  - rubocop-performance
Layout/ParameterAlignment:
  Enabled: false
Metrics/ClassLength:
  CountComments: false
  Max: 200
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
  CountComments: false
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'deployment/**/*'
Style/MixinUsage:
  Exclude:
    - 'lib/result.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'app/api/**/*'
Metrics/ParameterLists:
  Max: 7
  Exclude:
    - 'spec/features/**/*'
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'Capfile'
    - 'Rakefile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
Style/Lambda:
  EnforcedStyle: literal
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/FormatStringToken:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DateTime:
  Enabled: false
