AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**'
    - 'config/**'
    - 'script/**'
    - 'spec/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/SymbolArray:
  EnforcedStyle: brackets
Style/FormatStringToken:
  EnforcedStyle: unannotated
Style/DateTime:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Max: 130

