defaults:
  google_client_id: '101070241411-9li6klpo7sdc1vm4h3uoemljini81vfp.apps.googleusercontent.com'
  google_client_secret: 'qXKkREDrmXa5cb-wO89z6B8I'
  app_host: 'https://aqueous-tundra-26026.herokuapp.com'
