default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  tineout: 5000
  user: krzysiek
  password: '1234'

development:
  <<: *default
  database: fast_flashcards_development

test:
  <<: *default
  database: fast_flashcards_test

production:
  <<: *default
  database: fast_flashcards_production
