default: &default
  encoding: unicode
  pool: 5
  tineout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/fast_flashcards_development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/fast_flashcards_test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_production
