default: &default
  encoding: unicode
  pool: 5
  tineout: 5000

development:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_development

test:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_test

production:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_production
