default: &default
  encoding: unicode
  pool: 5
  # timeout: 5000
  # host: db
  # port: 5432
  # username: postgres

development:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_development

test:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_test

production:
  <<: *default
  adapter: postgresql
  database: fast_flashcards_production
